
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.MemberScalarFieldEnum = {
  userId: 'userId',
  handle: 'handle',
  handleLower: 'handleLower',
  email: 'email',
  verified: 'verified',
  skillScore: 'skillScore',
  memberRatingId: 'memberRatingId',
  firstName: 'firstName',
  lastName: 'lastName',
  description: 'description',
  otherLangName: 'otherLangName',
  status: 'status',
  newEmail: 'newEmail',
  emailVerifyToken: 'emailVerifyToken',
  emailVerifyTokenDate: 'emailVerifyTokenDate',
  newEmailVerifyToken: 'newEmailVerifyToken',
  newEmailVerifyTokenDate: 'newEmailVerifyTokenDate',
  country: 'country',
  homeCountryCode: 'homeCountryCode',
  competitionCountryCode: 'competitionCountryCode',
  photoURL: 'photoURL',
  tracks: 'tracks',
  loginCount: 'loginCount',
  lastLoginDate: 'lastLoginDate',
  availableForGigs: 'availableForGigs',
  availableForGigsLastUpdateDate: 'availableForGigsLastUpdateDate',
  lastProfileConfirmationDate: 'lastProfileConfirmationDate',
  skillScoreDeduction: 'skillScoreDeduction',
  namesAndHandleAppearance: 'namesAndHandleAppearance',
  aggregatedSkills: 'aggregatedSkills',
  enteredSkills: 'enteredSkills',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberAddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  streetAddr1: 'streetAddr1',
  streetAddr2: 'streetAddr2',
  city: 'city',
  zip: 'zip',
  stateCode: 'stateCode',
  type: 'type',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberPhoneScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  number: 'number',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberMaxRatingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  rating: 'rating',
  track: 'track',
  subTrack: 'subTrack',
  ratingColor: 'ratingColor',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberFinancialScalarFieldEnum = {
  userId: 'userId',
  amount: 'amount',
  status: 'status',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberStatsHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  trackId: 'trackId',
  typeId: 'typeId',
  challengeId: 'challengeId',
  mostRecent: 'mostRecent',
  oldRating: 'oldRating',
  newRating: 'newRating',
  placement: 'placement',
  percentile: 'percentile',
  oldVolatility: 'oldVolatility',
  newVolatility: 'newVolatility',
  oldGlobalRank: 'oldGlobalRank',
  newGlobalRank: 'newGlobalRank',
  oldCountryRank: 'oldCountryRank',
  newCountryRank: 'newCountryRank',
  oldSchoolRank: 'oldSchoolRank',
  newSchoolRank: 'newSchoolRank',
  eventDate: 'eventDate',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberStatsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  trackId: 'trackId',
  typeId: 'typeId',
  challenges: 'challenges',
  wins: 'wins',
  mostRecentSubmission: 'mostRecentSubmission',
  mostRecentEventDate: 'mostRecentEventDate',
  rating: 'rating',
  avgRank: 'avgRank',
  avgNumSubmissions: 'avgNumSubmissions',
  bestRank: 'bestRank',
  globalRank: 'globalRank',
  countryRank: 'countryRank',
  schoolRank: 'schoolRank',
  volatility: 'volatility',
  maxRating: 'maxRating',
  minRating: 'minRating',
  topFiveFinishes: 'topFiveFinishes',
  topTenFinishes: 'topTenFinishes',
  isPrivate: 'isPrivate',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberChallengePointsScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  challengeName: 'challengeName',
  userId: 'userId',
  placement: 'placement',
  points: 'points',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  subscriptions: 'subscriptions',
  hobby: 'hobby',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitDeviceScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  deviceType: 'deviceType',
  manufacturer: 'manufacturer',
  model: 'model',
  operatingSystem: 'operatingSystem',
  osVersion: 'osVersion',
  osLanguage: 'osLanguage',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitSoftwareScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  softwareType: 'softwareType',
  name: 'name',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitServiceProviderScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  type: 'type',
  name: 'name',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitWorkScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  industry: 'industry',
  otherIndustry: 'otherIndustry',
  companyName: 'companyName',
  position: 'position',
  startDate: 'startDate',
  endDate: 'endDate',
  working: 'working',
  description: 'description',
  associatedSkills: 'associatedSkills',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitEducationScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  collegeName: 'collegeName',
  degree: 'degree',
  endYear: 'endYear',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitBasicInfoScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  userId: 'userId',
  country: 'country',
  primaryInterestInTopcoder: 'primaryInterestInTopcoder',
  tshirtSize: 'tshirtSize',
  gender: 'gender',
  shortBio: 'shortBio',
  birthDate: 'birthDate',
  currentLocation: 'currentLocation',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitLanguageScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  language: 'language',
  spokenLevel: 'spokenLevel',
  writtenLevel: 'writtenLevel',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitOnboardChecklistScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  listItemType: 'listItemType',
  date: 'date',
  message: 'message',
  status: 'status',
  skip: 'skip',
  metadata: 'metadata',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitPersonalizationScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  key: 'key',
  value: 'value',
  private: 'private',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberTraitCommunityScalarFieldEnum = {
  id: 'id',
  memberTraitId: 'memberTraitId',
  communityName: 'communityName',
  status: 'status',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.MemberStatus = exports.$Enums.MemberStatus = {
  UNVERIFIED: 'UNVERIFIED',
  ACTIVE: 'ACTIVE',
  INACTIVE_USER_REQUEST: 'INACTIVE_USER_REQUEST',
  INACTIVE_DUPLICATE_ACCOUNT: 'INACTIVE_DUPLICATE_ACCOUNT',
  INACTIVE_IRREGULAR_ACCOUNT: 'INACTIVE_IRREGULAR_ACCOUNT',
  UNKNOWN: 'UNKNOWN'
};

exports.FinancialStatus = exports.$Enums.FinancialStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

exports.DeviceType = exports.$Enums.DeviceType = {
  Console: 'Console',
  Desktop: 'Desktop',
  Laptop: 'Laptop',
  Smartphone: 'Smartphone',
  Tablet: 'Tablet',
  Wearable: 'Wearable',
  Other: 'Other'
};

exports.SoftwareType = exports.$Enums.SoftwareType = {
  DeveloperTools: 'DeveloperTools',
  Browser: 'Browser',
  Productivity: 'Productivity',
  GraphAndDesign: 'GraphAndDesign',
  Utilities: 'Utilities'
};

exports.ServiceProviderType = exports.$Enums.ServiceProviderType = {
  InternetServiceProvider: 'InternetServiceProvider',
  MobileCarrier: 'MobileCarrier',
  Television: 'Television',
  FinancialInstitution: 'FinancialInstitution',
  Other: 'Other'
};

exports.WorkIndustryType = exports.$Enums.WorkIndustryType = {
  Banking: 'Banking',
  ConsumerGoods: 'ConsumerGoods',
  Energy: 'Energy',
  Entertainment: 'Entertainment',
  HealthCare: 'HealthCare',
  Pharma: 'Pharma',
  PublicSector: 'PublicSector',
  TechAndTechnologyService: 'TechAndTechnologyService',
  Telecoms: 'Telecoms',
  TravelAndHospitality: 'TravelAndHospitality',
  Other: 'Other'
};

exports.Prisma.ModelName = {
  member: 'member',
  memberAddress: 'memberAddress',
  memberPhone: 'memberPhone',
  memberMaxRating: 'memberMaxRating',
  memberFinancial: 'memberFinancial',
  memberStatsHistory: 'memberStatsHistory',
  memberStats: 'memberStats',
  memberChallengePoints: 'memberChallengePoints',
  memberTraits: 'memberTraits',
  memberTraitDevice: 'memberTraitDevice',
  memberTraitSoftware: 'memberTraitSoftware',
  memberTraitServiceProvider: 'memberTraitServiceProvider',
  memberTraitWork: 'memberTraitWork',
  memberTraitEducation: 'memberTraitEducation',
  memberTraitBasicInfo: 'memberTraitBasicInfo',
  memberTraitLanguage: 'memberTraitLanguage',
  memberTraitOnboardChecklist: 'memberTraitOnboardChecklist',
  memberTraitPersonalization: 'memberTraitPersonalization',
  memberTraitCommunity: 'memberTraitCommunity'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
